/**
 * Icon Map — curated set of FluentUI 24px icons for tab customization.
 *
 * Each entry maps a human-readable name to a React component.
 * Keep sorted alphabetically for the icon picker grid.
 */

import {
  Alert24Regular,
  Apps24Regular,
  Archive24Regular,
  ArrowSync24Regular,
  Beaker24Regular,
  Board24Regular,
  Bot24Regular,
  BrainCircuit24Regular,
  Briefcase24Regular,
  Bug24Regular,
  Building24Regular,
  Calendar24Regular,
  Chat24Regular,
  Checkmark24Regular,
  ClipboardTask24Regular,
  Clock24Regular,
  Cloud24Regular,
  Code24Regular,
  Collections24Regular,
  DataHistogram24Regular,
  Database24Regular,
  Document24Regular,
  DocumentEdit24Regular,
  DocumentSearch24Regular,
  Eye24Regular,
  Filter24Regular,
  Flag24Regular,
  Folder24Regular,
  Globe24Regular,
  Heart24Regular,
  Home24Regular,
  Info24Regular,
  Key24Regular,
  Lightbulb24Regular,
  Link24Regular,
  List24Regular,
  Location24Regular,
  LockClosed24Regular,
  Mail24Regular,
  Map24Regular,
  Megaphone24Regular,
  Organization24Regular,
  People24Regular,
  Person24Regular,
  Play24Regular,
  Pulse24Regular,
  Rocket24Regular,
  Search24Regular,
  Settings24Regular,
  Shield24Regular,
  Star24Regular,
  Table24Regular,
  Tag24Regular,
  Target24Regular,
  Toolbox24Regular,
  Warning24Regular,
  Wrench24Regular,
} from '@fluentui/react-icons'

export const ICON_MAP = {
  'Alert24Regular': Alert24Regular,
  'Apps24Regular': Apps24Regular,
  'Archive24Regular': Archive24Regular,
  'ArrowSync24Regular': ArrowSync24Regular,
  'Beaker24Regular': Beaker24Regular,
  'Board24Regular': Board24Regular,
  'Bot24Regular': Bot24Regular,
  'BrainCircuit24Regular': BrainCircuit24Regular,
  'Briefcase24Regular': Briefcase24Regular,
  'Bug24Regular': Bug24Regular,
  'Building24Regular': Building24Regular,
  'Calendar24Regular': Calendar24Regular,
  'Chat24Regular': Chat24Regular,
  'Checkmark24Regular': Checkmark24Regular,
  'ClipboardTask24Regular': ClipboardTask24Regular,
  'Clock24Regular': Clock24Regular,
  'Cloud24Regular': Cloud24Regular,
  'Code24Regular': Code24Regular,
  'Collections24Regular': Collections24Regular,
  'DataHistogram24Regular': DataHistogram24Regular,
  'Database24Regular': Database24Regular,
  'Document24Regular': Document24Regular,
  'DocumentEdit24Regular': DocumentEdit24Regular,
  'DocumentSearch24Regular': DocumentSearch24Regular,
  'Eye24Regular': Eye24Regular,
  'Filter24Regular': Filter24Regular,
  'Flag24Regular': Flag24Regular,
  'Folder24Regular': Folder24Regular,
  'Globe24Regular': Globe24Regular,
  'Heart24Regular': Heart24Regular,
  'Home24Regular': Home24Regular,
  'Info24Regular': Info24Regular,
  'Key24Regular': Key24Regular,
  'Lightbulb24Regular': Lightbulb24Regular,
  'Link24Regular': Link24Regular,
  'List24Regular': List24Regular,
  'Location24Regular': Location24Regular,
  'LockClosed24Regular': LockClosed24Regular,
  'Mail24Regular': Mail24Regular,
  'Map24Regular': Map24Regular,
  'Megaphone24Regular': Megaphone24Regular,
  'Organization24Regular': Organization24Regular,
  'People24Regular': People24Regular,
  'Person24Regular': Person24Regular,
  'Play24Regular': Play24Regular,
  'Pulse24Regular': Pulse24Regular,
  'Rocket24Regular': Rocket24Regular,
  'Search24Regular': Search24Regular,
  'Settings24Regular': Settings24Regular,
  'Shield24Regular': Shield24Regular,
  'Star24Regular': Star24Regular,
  'Table24Regular': Table24Regular,
  'Tag24Regular': Tag24Regular,
  'Target24Regular': Target24Regular,
  'Toolbox24Regular': Toolbox24Regular,
  'Warning24Regular': Warning24Regular,
  'Wrench24Regular': Wrench24Regular,
}

export const ICON_NAMES = Object.keys(ICON_MAP)
